#!/bin/busybox sh

# Mounts Kernel Virtual File Systems
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

# Create an device console
mknod /dev/console c 5 1

# Execute the Rust program!
echo "Starting RustScreen..."
exec /usr/local/bin/rustscreen-app
